//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventiqonEntities : DbContext
    {
        public EventiqonEntities()
            : base("name=EventiqonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivnost> Aktivnost { get; set; }
        public virtual DbSet<Dogodek> Dogodek { get; set; }
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<IzbrisanRacun> IzbrisanRacun { get; set; }
        public virtual DbSet<Kraj> Kraj { get; set; }
        public virtual DbSet<Naslov> Naslov { get; set; }
        public virtual DbSet<Obvestilo> Obvestilo { get; set; }
        public virtual DbSet<PostavkaAktivnosti> PostavkaAktivnosti { get; set; }
        public virtual DbSet<PostavkaDogodka> PostavkaDogodka { get; set; }
        public virtual DbSet<PotrditvenaKoda> PotrditvenaKoda { get; set; }
        public virtual DbSet<SeznamAktivnosti> SeznamAktivnosti { get; set; }
        public virtual DbSet<SeznamDogodkov> SeznamDogodkov { get; set; }
        public virtual DbSet<Uporabnik> Uporabnik { get; set; }
    }
}
