//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzbrisanRacun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzbrisanRacun()
        {
            this.Uporabnik1 = new HashSet<Uporabnik>();
        }
    
        public string uprabniskoIme { get; set; }
        public string razlog { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual Uporabnik Uporabnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uporabnik> Uporabnik1 { get; set; }
    }
}
