//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naslov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naslov()
        {
            this.Uporabnik = new HashSet<Uporabnik>();
        }
    
        public int idNaslov { get; set; }
        public int idKraj { get; set; }
        public string kraticaDrzave { get; set; }
        public int hisnaStevilka { get; set; }
        public string ulica { get; set; }
    
        public virtual Drzava Drzava { get; set; }
        public virtual Kraj Kraj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uporabnik> Uporabnik { get; set; }
    }
}
