//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostavkaDogodka
    {
        public int id2 { get; set; }
        public int idPostavkaDogodka { get; set; }
        public string naziv { get; set; }
        public string casovniOpisKdaj { get; set; }
        public string opisCasaTrajanja { get; set; }
        public string polniOpis { get; set; }
    
        public virtual Dogodek Dogodek { get; set; }
    }
}
