//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotrditvenaKoda
    {
        public string uporabniskoIme { get; set; }
        public string koda { get; set; }
        public System.DateTime datumVnosa { get; set; }
        public System.DateTime datumPoteka { get; set; }
    }
}
