//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uporabnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uporabnik()
        {
            this.Obvestilo = new HashSet<Obvestilo>();
            this.SeznamAktivnosti = new HashSet<SeznamAktivnosti>();
            this.SeznamDogodkov = new HashSet<SeznamDogodkov>();
        }
    
        public string uprabniskoIme { get; set; }
        public int idNaslov { get; set; }
        public string Izb_uprabniskoIme { get; set; }
        public string email { get; set; }
        public string Ime { get; set; }
        public string Priimek { get; set; }
        public string recoveryEmail { get; set; }
        public Nullable<System.DateTime> datumRojstva { get; set; }
        public string geslo { get; set; }
        public string telefon { get; set; }
        public string paypalRacun { get; set; }
    
        public virtual IzbrisanRacun IzbrisanRacun { get; set; }
        public virtual IzbrisanRacun IzbrisanRacun1 { get; set; }
        public virtual Naslov Naslov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obvestilo> Obvestilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeznamAktivnosti> SeznamAktivnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeznamDogodkov> SeznamDogodkov { get; set; }
    }
}
