//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzbrisanRacun
    {
        public string uprabniskoIme { get; set; }
        public string razlog { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual Uporabnik Uporabnik { get; set; }
    }
}
