//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostavkaAktivnosti
    {
        public int idAktivnost { get; set; }
        public int idPostavkaAktivnosti { get; set; }
        public string naziv { get; set; }
        public string casovniOpisKdaj { get; set; }
        public string opisCasaTrajanja { get; set; }
        public string polniOpis { get; set; }
    
        public virtual Aktivnost Aktivnost { get; set; }
    }
}
