//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiqonWebApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeznamDogodkov
    {
        public string uprabniskoIme { get; set; }
        public int idDogodek { get; set; }
        public int idSeznamDogodkov { get; set; }
        public string statusUdelezbe { get; set; }
        public int steviloVstopnic { get; set; }
        public Nullable<decimal> cena { get; set; }
    
        public virtual Dogodek Dogodek { get; set; }
        public virtual Uporabnik Uporabnik { get; set; }
    }
}
